python ./multiproc.py \
    --nproc_per_node 8 ./main.py /data/imagenet \
    --data-backend pytorch \
    --raport-file raport.json -j8 \
    -p 100 --lr 1.024 \
    --optimizer-batch-size 1024 \
    --warmup 8 \
    --arch resnet50 \
    -c fanin \
    --label-smoothing 0.1 \
    --lr-schedule cosine \
    --mom 0.875 \
    --wd 3.0517578125e-05 \
    -b 128 \
    --amp \
    --static-loss-scale 128 \
    --epochs 250 \
    --mixup 0.2 \
    --grow_prune \
    --delta_T 2 \
    --T_max 180 \
    --init_channel_ratio 0.3 \
    --channel_sparsity 0.7